### ISSUE TITLE
Block diagram

### ISSUE THREAD

**Issue by rahman-tud** [PeterOgden/ZCU104_VideoDemo#3]
Thank you for such an amazing project. I am quite new to this but I think. the tcl file is not supported in PYNQ anymore. So i need to build the project again. I already have exported the IPs using your code. Can you please share vivado block diagram or the project? that will be a life-saving help. 
Thank you.

**Comment by PeterOgden** [comment]
The base_logo.tcl file is the script used to regenerate the block diagram. You might need to edit it to add both the IP repo in this repository and the PYNQ IP repo (boards/ip in the main PYNQ git repository).

I've added the HWH file in the most recent commit.
